version: 1.0.{build}

init:
- cmd: java -version 2>&1 | find "version"

clone_script:
- cmd: git clone --recursive https://github.com/OpenRefine/OpenRefine
environment:
  ANT_HOME: C:\apache-ant-1.10.1
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

matrix:
  fast_finish: true

install:
- cmd: if not exist %ANT_HOME% pushd . && cd \ && appveyor DownloadFile http://apache.spinellicreations.com/ant/binaries/apache-ant-1.10.1-bin.zip && 7z x apache-ant-1.10.1-bin.zip && popd

cache:
- C:\apache-ant-1.10.1
- apache-ant-1.10.1-bin.zip
build: off

# scripts to run before build
before_build:
- cmd: echo Running scripts before build...
- cmd: cp extensions\database\test\conf\appveyor_int_tests.xml extensions\database\test\conf\int_tests.xml
- cmd: >-
    $env:MYSQL_PWD="password"
    $cmd = '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -e "create database test_db;" --user=root'
    iex "& $cmd"
    $cmd = '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -u root test_db < extensions/database/test/conf/travis-mysql.sql'
    iex "& $cmd"


build_script:
# - cmd: >-
#    echo Running refine build...
#    
#    cd OpenRefine
#    
#    refine build

test_script:
- cmd: echo Running test_script...
- cmd: >-
    echo PATH is:

    path

    cd OpenRefine

    refine server_test
    
    refine extensions_test
