version: 1.0.{build}

services:
- mysql
- postgresql96

init:
- cmd: java -version 2>&1 | find "version"

clone_depth: 5
skip_branch_with_pr: true

environment:
  ANT_HOME: C:\apache-ant-1.10.1
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

matrix:
  fast_finish: true

install:
- cmd: if not exist %ANT_HOME% pushd . && cd \ && appveyor DownloadFile http://apache.spinellicreations.com/ant/binaries/apache-ant-1.10.1-bin.zip && 7z x apache-ant-1.10.1-bin.zip && popd

cache:
- C:\apache-ant-1.10.1
- apache-ant-1.10.1-bin.zip
build: off

# scripts to run before test
before_test:
- cmd: echo Running scripts before build...
- cmd: |-
    PATH=C:\Program Files\PostgreSQL\9.6\bin\;C:\Program Files\MySQL\MySQL Server 5.7\bin\;%PATH%
    SET MYSQL_PWD="Password12!"
    mysql -u root --password=Password12! -e "create database test_db;"
    mysql -u root test_db --password=Password12! < extensions\database\test\conf\travis-mysql.sql
    SET PGUSER="postgres"
    SET PGPASSWORD="Password12!"
    psql -U postgres -c 'CREATE DATABASE test_db;'
    psql -U postgres test_db < extensions\database\test\conf\travis-pgsql.sql
    copy extensions\database\test\conf\appveyor_int_tests.xml extensions\database\test\conf\int_tests.xml

test_script:
- cmd: echo Running test_script...
- cmd: >-
    echo PATH is:

    path

    refine server_test
  
    refine extensions_test
